### ISSUE TITLE
Is there any way to get the code for PLuM？

### ISSUE THREAD

**Issue by zhaoyu24** [vb44/SiMpLE#1]
I've been following another one of your articles “Real-time 6-dof pose estimation of known geometries in point cloud data” ，it's alse a great work. I want to test this algorithm with my own dataset. Is there any way to get the code for this article? I would be honored to have your guidance！

**Comment by vb44** [comment]
Hi,

Thank you for your interest in PLuM!
There is an open-source repository for PLuM but it is down for maintenance currently. I should have it ready in around a week. I will post an update here when it is back online.

Thanks,
Vedant

**Comment by zhaoyu24** [comment]
> Hi,
> 
> Thank you for your interest in PLuM! There is an open-source repository for PLuM but it is down for maintenance currently. I should have it ready in around a week. I will post an update here when it is back online.
> 
> Thanks, Vedant

Thank you very much！

**Comment by vb44** [comment]
Hi,

Please find the open source repository at: [PLuM](https://github.com/vb44/Pose-Lookup-Method).
Feel free to post any queries on the PLuM page.

Thanks,
Vedant
