### ISSUE TITLE
Almost consumed ALL CPU

### ISSUE THREAD

**Issue by hannibal051** [vb44/SiMpLE#2]
On one Intel i9-14900KF CPU, when using the default parameters, all CPU resources are above 50%. Is there any way to run the code on a single CPU with real-time performance?
### Algorithm configuration.
sigma: 0.35
rMap: 2
rNew: 0.5
convergenceTol: 1e-3
minSensorRange: 5
### Hardware configuration.
maxSensorRange: 120
![image](https://github.com/vb44/SiMpLE/assets/60796213/9a495535-a3de-4fa3-903c-83326d17e7d4)

**Comment by vb44** [comment]
Hi,
A few notes,
- The real-time applicability relies heavily on having the ability to thread the objective function.
- The testing in the paper is performed with an Intel Core i7-10700K CPU @ 3.80GHz × 16.
- I'm currently using Intel's TBB library to parallelize the objective function. This automatically allocates available threads to perform the task. I have also tested using OpenMP (see the plot below) and achieved real-time performance with a minimum of four threads.
- A simple example of using OpenMP for the objective function is provided at *main/archive/usingOpenMP* for an older version of the code but should be easy to see the main difference I have highlighted below. To build this, you will need to include "omp.h" and link OpenMP in the CMakeLists as shown in the *main/archive/usingOpenMP/CMakeLists.txt* file.

Current objective function parallelization using TBB (ObjectiveFunction.cpp lines 31 to 56):
```cpp
  // Calculate the hypothesis reward.
  // Loop through each transformed target scan and find the closest point
  // in the source scan.
  tbb::parallel_for(
  tbb::blocked_range<int>(0, scan_.size()),
  [&](tbb::blocked_range<int> r)
  {
      for (unsigned int i = r.begin(); i < r.end(); i++)
      {
          uint32_t retIndex;
          double outDistSqr;
          double query_pt[3];
          Eigen::Vector4d ptTf = hypothesis*scan_[i];
          query_pt[0] = ptTf(0); 
          query_pt[1] = ptTf(1);
          query_pt[2] = ptTf(2);
          
          // Search for the closest point.
          subMapKdTree_->knnSearch(&query_pt[0], numResults, &retIndex,
                                   &outDistSqr);

          // Score the difference between the current and nearest point,
          // Equation 5.
          scores[i] = exp(-outDistSqr * sigma_);
      }
  });
```
Using OpenMP you can se the number of threads and the section would be:
```cpp
  // Calculate the hypothesis reward.
  // Loop through each transformed target scan and find the closest point
  // in the source scan.
  omp_set_num_threads(10); // Manually set the number of threads.
  #pragma omp parallel for
  for (unsigned int i = 0; i < scan_.size(); i++)
  {
          uint32_t retIndex;
          double outDistSqr;
          double query_pt[3];
          Eigen::Vector4d ptTf = hypothesis*scan_[i];
          query_pt[0] = ptTf(0); 
          query_pt[1] = ptTf(1);
          query_pt[2] = ptTf(2);
            
          // Search for the closest point.
          subMapKdTree_->knnSearch(&query_pt[0], numResults, &retIndex,
                                     &outDistSqr);

          // Score the difference between the current and nearest point,
          // Equation 5.
          scores[i] = exp(-outDistSqr * sigma_);
  }
```
Please let me know if there are any questions.
Thanks,
Vedant

![SimpleOpenMpPerformance](https://github.com/vb44/SiMpLE/assets/63623876/944a0256-549a-4258-bb9b-f09a0fb0960b)
