### ISSUE TITLE
Clarification on Evaluation Results in KITTI Dataset  

### ISSUE THREAD

**Issue by hanm2019** [vb44/SiMpLE#3]
Hi authors,  

First, I would like to thank you for your excellent open-source code. I recently tested it on the KITTI dataset and evaluated the results using the provided `devkit` tools. Here are some key findings from my testing:  

1. **Error on `seq00`:**  
   The error I obtained was:
   - Translation Error: **86.1732**  
   - Rotation Error: **34.8329**  

   For this test, I used the configuration file `config_KITTI_offline.yaml`.

Thank you again for your work, and I look forward to your response.

**Comment by hanm2019** [comment]
Here are some result:
```
$ ~/SiMpLE/devkit/build/evaluate_odometry ~/SiMpLE/sampleResults/KITTI/simpleOutputs/offline/00 ~/SiMpLE/sampleResults/KITTI/groundTruth/00.txt
86.1732, 34.8329
```
```
$ ~/SiMpLE/devkit/build/evaluate_odometry ~/SiMpLE/sampleResults/KITTI/estimatesInGroundTruthFrame/offline/00.txt ~/SiMpLE/sampleResults/KITTI/groundTruth/00.txt
0.511501, 0.180865
```

```
$ ~/SiMpLE/devkit/build/evaluate_odometry ~/SiMpLE/sampleResults/KITTI/estimatesInGroundTruthFrame/offline/00.txt ~/KITTI/dataset/sequences/00/poses.txt
0.48395, 0.249508
```

```
$ ~/SiMpLE/devkit/build/evaluate_odometry ~/SiMpLE/sampleResults/KITTI/simpleOutputs/offline/00  ~/KITTI/dataset/sequences/00/poses.txt
86.1401, 34.8512
```

I am confuse about the `estimatesInGroundTruthFrame` folder and `simpleOutputs`

**Comment by vb44** [comment]
Hi,

Thank you for reaching out!
The folders in SiMpLE/sampleResults/KITTI/ contains:

- **_simpleOutputs_**: This folder includes the trajectory output files from SiMpLE directly. These estimates are in the sensor (Velodyne) frame.
- **_estimatesInGroundTruthFrame_**: This folder includes the SiMpLE trajectory estimates transformed into the camera frame. This is achieved by applying the sensor calibration (from the KITTI dataset) to the trajectory estimates in the **_simpleOutputs_** folder.
- **_groundTruth_**: This folder includes a copy of the trajectory estimates in the camera frame from the KITTI dataset.

The trajectories in **_simpleOutputs_** must be converted to the camera frame by applying the Velodyne to camera registration to generate the trajectories in **_estimatesInGroundTruthFrame_**. Once the trajectories are in the camera frame, they can be compared with the ground truth in the **_groundTruth_** folder.
This explains why the second command produces the correct result,
```
$ ~/SiMpLE/devkit/build/evaluate_odometry ~/SiMpLE/sampleResults/KITTI/estimatesInGroundTruthFrame/offline/00.txt ~/SiMpLE/sampleResults/KITTI/groundTruth/00.txt
0.511501, 0.180865
```
whereas the first command compares trajectories in two different frames.

I hope this clarifies the issue!
Please let us know if there are any questions :)

**Comment by hanm2019** [comment]
Thanks for your response!
I tried to convert the trajectory using `Tr_velo_to_cam` in calib.txt, but the result seems to still have some small deviation from estimatesInGroundTruthFrame.
The Tr_velo_to_cam is :
```
Tr_velo_to_cam = np.array([
    [7.533745e-03, -9.999714e-01, -6.166020e-04, -4.069766e-03],
    [1.480249e-02, 7.280733e-04, -9.998902e-01, -7.631618e-02],
    [9.998621e-01, 7.523790e-03, 1.480755e-02, -2.717806e-01]
])
```

My python code is:
```
for pose in poses:

        pose_h = np.eye(4)
        pose_h[:3, :] = pose
        transformed_pose_h = Tr_velo_to_cam_h @ pose_h

        transformed_pose = transformed_pose_h[:3, :]
        transformed_poses.append(transformed_pose)
```

**Comment by vb44** [comment]
Hi,
An example of how the calibration should be applied is shown below (source: [KISS_ICP](https://github.com/PRBonn/kiss-icp/blob/main/python/kiss_icp/datasets/kitti.py))
```python
def apply_calibration(self, poses: np.ndarray) -> np.ndarray:
        """Converts from Velodyne to Camera Frame"""
        Tr = np.eye(4, dtype=np.float64)
        Tr[:3, :4] = self.calibration["Tr"].reshape(3, 4)
        return Tr @ poses @ np.linalg.inv(Tr)
```

**Comment by hanm2019** [comment]
Thanks!
